## NumPy
NumpPy is the fundamental package for scientific computing in python. At the core, NumPy package is the ndarray object.

Almost all python projects thesdays have NumPy usage in them. `Pandas`, `Matplotlib`, and `Scikit-Learn` are built on top of NumPy.

NumPy has some important difference when compared to standard python Sequence.
1. NumPy arrays have a `fixed size at creation`, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
2. The elements in a NumPy array are all required to be of the `same data type, and thus will be the same size in memory`. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.


**Arrays** are a collection of elements/values, that can have one or more dimensions. `An array of one dimension is called a Vector while having two dimensions is called a Matrix.`

**NumPy** arrays are called **ndarray** or **N-dimensional arrays** and they store elements of the same type and size. It is known for its high-performance and provides efficient storage and data operations as arrays grow in size.


## Usage
Import the package as a namespace
```python
import numpy as np
```

1. Defining an ndarray
    - `np.array(), np.ones(), np.zeros(), np.empty(), np.full(), np.eye()`
    - `np.arange(), np.linspace()`
    - `np.random.random()` : np.random has many methods, Search - DYI
2. Some attributes of ndarray
    - `ndarray.ndim`
    - `ndarray.shape`
    - `ndarray.size`
    - `ndarray.dtype`
    - `ndarray.data`
    - `ndarray.reshape()`
3. Basic operation
    - `ndarray.flatten(), ndarray.ravel()` : to convert n-dimentional array to 1-D
    - `ndarray.transpose()` : Convert X-axis to Y-axis
    - slicing format `[start:stop:step-size]`
    - `np.vstack()` : stack arrays on top of each other
    - `np.hstack()` : stack arrays side by side
    - `np.concatenate()` : vstack and hstack can be performed along axis
    - `np.sort()`
    - `np.split()` : split the array into sub-arrays
4. Universal functions `more about:` [ufunc](https://docs.scipy.org/doc/numpy-1.3.x/reference/ufuncs.html#available-ufuncs): All these functions are perfomed elementwise on the matrix.
    - `np.sin(), np.cos(), np.tan()`
    - `np.arcsin(), np.arccos(), np.arctan()` : Inverse
    - `np.hypot()` : hypotenuse
    - `np.sinh(), np.cosh(), np.tanh()`
    - `np.arcsinh(), np.arccosh(), np.arctanh()` : Inverse
    - `np.deg2rad(), np.rad2deg()`
    - `np.max(), np.amax(), np.min(), np.amin()`
    - `np.median(), np.mean(), np.std(), np.var(), np.average()`
    - `np.floor(), np.ceil(), np.trunc(), np.mod(), np.fmod(), np.modf()`
    - `np.isnan(), np.power(), np.absolute(), np.exp(), np.log()`
    - `+, *, -, /` : ndarray direct operation using opreator
    - `np.where()`
    
    
    
    
**Extras:**
- `axis 0` is the first axis, its the direction along the rows. it runs downwards
- `axis 1` is the direction along columns, it runs across

## EXERCISE

In [1]:
# Importing NumPy and printing version number
import numpy as np
np.__version__

'1.20.3'

In [2]:
# Create a zero array
a1 = np.zeros(shape=(1,5))
a1

array([[0., 0., 0., 0., 0.]])

In [3]:
# Element-wise addition of 2 numpy arrays
a1 = np.random.random(size=(3,2))
a1

array([[0.50471463, 0.68291244],
       [0.80433269, 0.27968192],
       [0.28947989, 0.81968011]])

In [4]:
a2 = np.random.random(size=(3,2))
a2

array([[0.99959251, 0.64699866],
       [0.4548119 , 0.86613274],
       [0.45416962, 0.29759142]])

In [5]:
a1 + a2

array([[1.50430713, 1.3299111 ],
       [1.25914459, 1.14581466],
       [0.74364951, 1.11727153]])

In [6]:
# Multiplying a matrix (numpy array) by a scalar
val = 5
a1 = np.array([[1,2,4], [11,22,33]])
print("Before")
print(a1)

print("After")
5 * a1

Before
[[ 1  2  4]
 [11 22 33]]
After


array([[  5,  10,  20],
       [ 55, 110, 165]])

In [7]:
# create a identity Matrix
e = np.eye(N=3, M=4, k=0)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [8]:
# Array re-dimensioning
arr1 = np.eye(N=3, M=4, k=0)
arr1.shape

(3, 4)

In [9]:
arr1.reshape((6,2))

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.]])

In [10]:
# Array datatype conversion - Obtaining Boolean Array from Binary Array
arr2 = np.array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.]])
arr2

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.]])

In [11]:
arr3= arr2.astype('bool')
arr3

array([[ True, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [ True, False]])

In [12]:
# Horizontal Stacking of Numpy Arrays
a2 = np.random.random(size=(1,5))
a1 = np.random.random(size=(1,5))
print(a1)
print(a2)

[[0.6377334  0.5308792  0.01250028 0.95387525 0.64597131]]
[[0.6261321  0.35625058 0.24946421 0.14055723 0.01656466]]


In [13]:
np.hstack((a1,a2))

array([[0.6377334 , 0.5308792 , 0.01250028, 0.95387525, 0.64597131,
        0.6261321 , 0.35625058, 0.24946421, 0.14055723, 0.01656466]])

In [14]:
# Vertically Stacking of Numpy Arrays
np.vstack((a1,a2))

array([[0.6377334 , 0.5308792 , 0.01250028, 0.95387525, 0.64597131],
       [0.6261321 , 0.35625058, 0.24946421, 0.14055723, 0.01656466]])

In [15]:
# Sequence Generation
np.linspace(0, 20, num=10, dtype='int')

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [16]:
# Getting the positions (indexes) where elements of 2 numpy arrays match
a = np.array([[1,2,4], [3,4,5]])
b = np.array([[1,2,5], [1,4,7]])
np.where(a==b)

(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64))

In [17]:
# Generation of given count of equally spaced numbers within a specified range
np.linspace(0, 20, num=10, dtype='int')

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [18]:
# Matrix Generation with one particular value
np.full((3,3),fill_value=10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [19]:
# Array Generation of random integers within a specified range
np.random.randint(low=2, high=4, size=(3,3))

array([[2, 2, 2],
       [2, 2, 3],
       [3, 3, 3]])

In [20]:
# Array Generation of random numbers following normal distribution
np.random.normal(loc=3.0, scale=0.9, size=(2,3))

array([[1.85166354, 4.22234627, 3.48197607],
       [2.60143398, 2.51822624, 2.73461247]])

In [21]:
# Matrix Multiplication
a = np.array([[1,2,4], [3,4,5]])
b = np.array([[1,2], [1,4], [3,4]])
print(a, a.shape)
print(b, b.shape)

np.dot(a,b)

[[1 2 4]
 [3 4 5]] (2, 3)
[[1 2]
 [1 4]
 [3 4]] (3, 2)


array([[15, 26],
       [22, 42]])

In [22]:
# Matrix Transpose
c = np.array([[1,2], [1,4], [3,4]])
c.transpose()

array([[1, 1, 3],
       [2, 4, 4]])

In [23]:
# Generating the array element indexes such that the array elements appear in ascending order
d = np.array([[0, 11, 5, 10, 2]])
np.argsort(d)

array([[0, 4, 2, 3, 1]], dtype=int64)

In [24]:
from IPython.display import IFrame
IFrame('https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf', width=980, height=520)

## Practice set
[exercise](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)